
services:
  backend:
    container_name: backend-nestjs
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    env_file:
      - ./backend/.env
    networks:
      - app-network

  frontend:
    container_name: frontend-angular
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  backend_node_modules:

networks:
  app-network:
    driver: bridge
